"""Draw README desktops from synthetic chrome and untouched panel captures.

Run with Pillow installed: python compose.py [capture-directory].
The default inputs are /tmp/shots. All coordinates below are final PNG pixels;
the canvas is drawn at twice that resolution, then downsampled once.
Only supplied panel PNGs are read as image assets. Keep those source captures
with this script when archiving the task; they are not generated by this file.
"""

import math
import re
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont

ROOT = Path(__file__).resolve().parents[2]
SIZE = (1600, 1000)
RENDER = 2
MONO = (
    "/System/Library/Fonts/Menlo.ttc",
    "/System/Library/Fonts/Supplemental/Courier New.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
)
UI = (
    "/System/Library/Fonts/SFNS.ttf",
    "/System/Library/Fonts/Helvetica.ttc",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
)


def font(size: int, mono: bool = False) -> ImageFont.FreeTypeFont:
    for path in MONO if mono else UI:
        if Path(path).is_file():
            return ImageFont.truetype(path, size * RENDER, index=0)
    raise FileNotFoundError("No suitable UI or monospace font installed")


def box(bounds: tuple[float, ...]) -> tuple[int, ...]:
    return tuple(round(value * RENDER) for value in bounds)


def text(
    draw: ImageDraw.ImageDraw,
    xy: tuple[float, float],
    value: str,
    color: str = "#a3adb9",
    size: int = 18,
    mono: bool = False,
) -> None:
    draw.text(box(xy), value, font=font(size, mono), fill=color)


def wallpaper() -> Image.Image:
    small = Image.new("RGB", (400, 250))
    pixels = small.load()
    for y in range(250):
        for x in range(400):
            glow = math.exp(-(((x - 266) / 142) ** 2 + ((y - 130) / 105) ** 2))
            pixels[x, y] = (
                round(8 + 2 * glow),
                round(12 + 10 * glow + 2 * y / 250),
                round(21 + 13 * glow + 3 * y / 250),
            )
    return small.resize(box(SIZE), Image.Resampling.BICUBIC).convert("RGBA")


def window(
    scene: Image.Image, bounds: tuple[int, int, int, int], title: str
) -> ImageDraw.ImageDraw:
    x, y, w, h = bounds
    shadow = Image.new("RGBA", scene.size)
    ImageDraw.Draw(shadow).rounded_rectangle(
        box((x, y + 12, x + w, y + h + 12)), radius=18 * RENDER, fill=(0, 0, 0, 150)
    )
    scene.alpha_composite(shadow.filter(ImageFilter.GaussianBlur(22 * RENDER)))
    draw = ImageDraw.Draw(scene)
    draw.rounded_rectangle(
        box((x, y, x + w, y + h)),
        radius=12 * RENDER,
        fill="#151a23",
        outline="#343b47",
        width=RENDER,
    )
    draw.rounded_rectangle(
        box((x + 1, y + 1, x + w - 1, y + 43)),
        radius=11 * RENDER,
        fill="#242a35",
    )
    draw.rectangle(box((x + 1, y + 23, x + w - 1, y + 43)), fill="#242a35")
    for i, color in enumerate(("#df6a65", "#d8b65c", "#6ab880")):
        cx = x + 23 + i * 22
        draw.ellipse(box((cx - 6, y + 16, cx + 6, y + 28)), fill=color)
    title_font = font(16)
    width = draw.textlength(title, font=title_font) / RENDER
    text(draw, (x + (w - width) / 2, y + 12), title, "#b2bac6", 16)
    return draw


def desktop() -> Image.Image:
    scene = wallpaper()
    bar = Image.new("RGBA", scene.size)
    draw = ImageDraw.Draw(bar)
    draw.rectangle(box((0, 0, 1600, 48)), fill=(18, 23, 32, 210))
    draw.ellipse(box((25, 17, 39, 31)), fill="#b8c1cd")
    text(draw, (59, 11), "Finder", "#d9e0e9", 20)
    text(draw, (1501, 11), "9:41", "#d9e0e9", 20)
    for radius in (8, 14, 20):
        draw.arc(
            box((1396 - radius, 33 - radius, 1396 + radius, 33 + radius)),
            222,
            318,
            fill="#c6cfda",
            width=2 * RENDER,
        )
    draw.ellipse(box((1394, 29, 1398, 33)), fill="#c6cfda")
    draw.rounded_rectangle(
        box((1432, 17, 1469, 32)), radius=3 * RENDER, outline="#c6cfda", width=RENDER
    )
    draw.rectangle(box((1435, 20, 1461, 29)), fill="#aebbc9")
    draw.rectangle(box((1471, 21, 1474, 28)), fill="#c6cfda")
    scene.alpha_composite(bar)

    draw = window(scene, (94, 118, 880, 662), "PanelController.swift - ask-away")
    draw.rectangle(box((95, 162, 154, 760)), fill="#121720")
    code = [
        "import AppKit",
        "import SwiftUI",
        "",
        "@MainActor",
        "final class PanelRootView: NSView {",
        "    private var drainLayer: CAShapeLayer?",
        "    private var contentStack: NSView?",
        "",
        "    func configure(title: String) {",
        "        wantsLayer = true",
        "        layer?.masksToBounds = false",
        "",
        "        let rect = bounds.insetBy(dx: 28, dy: 28)",
        "        let content = NSView(frame: rect)",
        "        content.wantsLayer = true",
        "        addSubview(content)",
        "",
        "        let effect = NSVisualEffectView()",
        "        effect.material = .hudWindow",
        "        effect.blendingMode = .behindWindow",
        "        effect.state = .active",
        "        content.addSubview(effect)",
        "    }",
        "}",
    ]
    code_font = font(17, True)
    for index, line in enumerate(code, 1):
        y = 181 + (index - 1) * 23
        text(draw, (112, y), str(index).rjust(2), "#586477", 15, True)
        x = 173.0
        for token in re.split(
            r"(\b(?:import|final|class|private|var|func|let|true|false)\b)", line
        ):
            color = (
                "#af97c4"
                if token
                in {
                    "import",
                    "final",
                    "class",
                    "private",
                    "var",
                    "func",
                    "let",
                    "true",
                    "false",
                }
                else "#91a0b2"
            )
            text(draw, (x, y), token, color, 17, True)
            x += draw.textlength(token, font=code_font) / RENDER
    draw.line(box((95, 748, 973, 748)), fill="#2a3341", width=RENDER)
    text(
        draw,
        (112, 756),
        "Swift   UTF-8                                       ask-away",
        "#748296",
        13,
        True,
    )

    draw = window(scene, (665, 728, 838, 230), "zsh - ask-away")
    lines = [
        ("~/dev/ask-away % ask-away --questions-file demo.json", "#acbbc9"),
        ('{"results":[', "#8296a7"),
        ('  {"index":0,"status":"answered","answer":"Staging"}', "#8296a7"),
        ('],"stopped_at":1}', "#8296a7"),
        ("~/dev/ask-away %", "#92afb2"),
    ]
    for index, (line, color) in enumerate(lines):
        text(draw, (690, 799 + index * 29), line, color, 17, True)
    draw.rectangle(box((858, 915, 868, 933)), fill="#a9c4c7")
    return scene


def panel(scene: Image.Image, source: Path, xy: tuple[int, int], scale: float) -> None:
    with Image.open(source) as capture:
        asset = capture.convert("RGBA")
        asset = asset.resize(
            (round(asset.width * scale * RENDER), round(asset.height * scale * RENDER)),
            Image.Resampling.LANCZOS,
        )
        scene.alpha_composite(asset, box(xy))


def cursor(scene: Image.Image, xy: tuple[int, int]) -> None:
    x, y = xy
    points = [(0, 0), (0, 29), (7, 22), (13, 35), (19, 32), (13, 20), (24, 20)]
    draw = ImageDraw.Draw(scene)
    draw.polygon(
        [box((x + dx + 2, y + dy + 2)) for dx, dy in points], fill=(0, 0, 0, 130)
    )
    points = [box((x + dx, y + dy)) for dx, dy in points]
    draw.polygon(points, fill="#11151c")
    draw.line(points + [points[0]], fill="#eaf0f6", width=2 * RENDER, joint="curve")


def main() -> None:
    inputs = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/tmp/shots")
    output = ROOT / "docs"
    output.mkdir(exist_ok=True)
    base = desktop()
    hero = base.copy()
    panel(hero, inputs / "panel-hero.png", (600, 251), 0.8)
    cursor(hero, (1293, 722))
    batch = base.copy()
    panel(batch, inputs / "panel-batch.png", (215, 403), 1.0)
    cascade = base.copy()
    for index in range(3):
        panel(
            cascade,
            inputs / f"panel-cas{index + 1}.png",
            (490 + index * 48, 302 + index * 48),
            1.0,
        )
    for name, scene in (("panel", hero), ("batch", batch), ("cascade", cascade)):
        scene.convert("RGB").resize(SIZE, Image.Resampling.LANCZOS).save(
            output / f"{name}.png"
        )


if __name__ == "__main__":
    main()
